# Generated by Django 2.2 on 2019-05-05 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL à réduire')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('pseudo', models.CharField(max_length=100)),
                ('acces', models.IntegerField(default=0, verbose_name="Nombre d'accès à l'URL")),
            ],
            options={
                'verbose_name': 'url',
                'ordering': ['date'],
            },
        ),
    ]
