# Generated by Django 2.2 on 2019-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniurl',
            options={'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URL'},
        ),
        migrations.RenameField(
            model_name='miniurl',
            old_name='acces',
            new_name='nb_acces',
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='pseudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
