# Generated by Django 2.2 on 2019-05-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
