# Generated by Django 2.2 on 2019-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190504_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slugtest', max_length=100),
            preserve_default=False,
        ),
    ]
